### ISSUE TITLE
Bug in Perlin Noise at small scales

### ISSUE THREAD

**Issue by jpapon** [mgschwan/blensor#15]
So if you use a small scale with Perlin Noise (as the kinect sensor does), the indexing fails [here](https://github.com/mgschwan/blensor/blob/master/release/scripts/addons/blensor/noise.py#L11).

This conversion to int8 should be changed to int32 to avoid going out of range at small scales. In such cases (again, as with the kinect) the n parameter needs to be set higher as well (e.g. 512).

**Comment by mgschwan** [comment]
Fixed in trunk
