### ISSUE TITLE
Blensor crash when starting

### ISSUE THREAD

**Issue by frederico00** [mgschwan/blensor#16]
Hey,

I just compiled from source blensor,  and when i try to start it crah.

Writing: /tmp/blender.crash.txt

# Blender 2.74 (sub 1), Unknown revision

# backtrace
./blender(BLI_system_backtrace+0x1d) [0x1112b5d]
./blender() [0x83ae93]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40) [0x7f62cb76bd40]
./blender() [0xa1a5d6]
./blender(ui_draw_but+0x408) [0xa1ed28]
./blender(UI_block_draw+0x1aa) [0x9dac8a]
./blender(ED_region_header+0x1a8) [0xad3ca8]
./blender(ED_region_do_draw+0xa55) [0xad2875]
./blender(wm_draw_update+0x58c) [0x84096c]
./blender(WM_main+0x28) [0x83cea8]
./blender(main+0xd6f) [0x82e50f]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f62cb756ec5]
./blender() [0x83a8f7]

any idea?

**Comment by mgschwan** [comment]
Thank you for the report.
I've commited a fix for the crash on startup issue.

The reason is a corrupt startup file in the blensor trunk. It seems to affect all versions of Blensor starting with 1.16rc1. A temporary workaround is to download the official blender (if you are using Blensor 1.16 then it is Blender 2.72 and if you are using the current trunk then it is Blender 2.74), start it and save an empty startup file. The next time you start blensor it will use the new startup file instead of the one that is compiled in.

This issue should now be fixed

**Comment by frederico00** [comment]
Sorry, can you be more precise with what i need to do?

Thanks in advance

Melhores Cumprimentos,
--
Frederico Cabeço
Licenciado em Eng. Electrótecnica
Telm: (+351) 912376259

2015-04-21 9:06 GMT+01:00 Michael Gschwandtner <notifications@github.com>:

**Comment by frederico00** [comment]
Dear Michael,

I saw that you release a new binary version for linux, and it is working
fine.

My problem is that you change the settings for the TOF camera. Before i was
simulating a TOF camera, and i was able to have good results for the
recognition using PCL. Now i have somo more settings(focal lenght and 2
more ....) for the tof camera, and i can´t get the same results.

Is it possible to have the holder binary version for linux (then i create a
start up file)? Or maybe the values of those settings to equalize the
previus version ...


In windows when i try to write/run a script the blensor crashes ..... In
linux i can't have the same results....

Thanks in advance.







Melhores Cumprimentos,
--
Frederico Cabeço
Licenciado em Eng. Electrótecnica
Telm: (+351) 912376259

2015-04-26 15:46 GMT+01:00 Frederico Cabeço <cabeco.frederico@gmail.com>:

**Comment by mgschwan** [comment]
Dear Frederico, 

I was afraid that the change to the TOF code would cause some
compatibility issues. 

Can you send me a blend file from an earlier version where it was still
working properly. 

The problem with the old TOF code was that there was a bug due to which
the field of view could not be changed. 

Best regards 

Michael 

Am 02.06.2015 10:33, schrieb frederico00: 

> Dear Michael,
> 
> I saw that you release a new binary version for linux, and it is working
> fine.
> 
> My problem is that you change the settings for the TOF camera. Before i was
> simulating a TOF camera, and i was able to have good results for the
> recognition using PCL. Now i have somo more settings(focal lenght and 2
> more ....) for the tof camera, and i can´t get the same results.
> 
> Is it possible to have the holder binary version for linux (then i create a
> start up file)? Or maybe the values of those settings to equalize the
> previus version ...
> 
> In windows when i try to write/run a script the blensor crashes ..... In
> linux i can't have the same results....
> 
> Thanks in advance.
> 
> Melhores Cumprimentos,
> --
> Frederico Cabeço
> Licenciado em Eng. Electrótecnica
> Telm: (+351) 912376259
> 
> 2015-04-26 15:46 GMT+01:00 Frederico Cabeço <cabeco.frederico@gmail.com>:
> 
>> Sorry, can you be more precise with what i need to do?
>>
>> Thanks in advance
>>
>> Melhores Cumprimentos,
>> --
>> Frederico Cabeço
>> Licenciado em Eng. Electrótecnica
>> Telm: (+351) 912376259
>>
>> 2015-04-21 9:06 GMT+01:00 Michael Gschwandtner <notifications@github.com>:
>>
>>> Thank you for the report.
>>> I've commited a fix for the crash on startup issue.
>>>
>>> The reason is a corrupt startup file in the blensor trunk. It seems to
>>> affect all versions of Blensor starting with 1.16rc1. A temporary
>>> workaround is to download the official blender (if you are using Blensor
>>> 1.16 then it is Blender 2.72 and if you are using the current trunk then it
>>> is Blender 2.74), start it and save an empty startup file. The next time
>>> you start blensor it will use the new startup file instead of the one that
>>> is compiled in.
>>>
>>> This issue should now be fixed
>>>
>>> --
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/mgschwan/blensor/issues/16#issuecomment-94693926>.
>>>
>>
>> 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1] https://github.com/mgschwan/blensor/issues/16#issuecomment-107862776

**Comment by frederico00** [comment]
Another point,

The referencial (X,Y,Z) form blensor is diferent from the referencial form
pcl.... I don't know if it is a blender definition that we can change...

For example z in blensor will be -z in pcl

Regards,
FC

Melhores Cumprimentos,
--
Frederico Cabeço
Licenciado em Eng. Electrótecnica
Telm: (+351) 912376259

2015-06-03 17:02 GMT+01:00 Michael Gschwandtner <notifications@github.com>:
