### ISSUE TITLE
Scan attribute

### ISSUE THREAD

**Issue by anxsy** [mgschwan/blensor#22]
Hi Michael,

I'm looking forward to applying your Blensor functionality to some of my school studies, it's the perfect tool I need for some case work. I just pulled your addon into Blender 2.79 but am getting an error I'm having trouble working around right off the bat:

File "~/blensor/_init_.py", line 507, in invoke dispatch_scan(obj) 
AbsoluteError: 'object' object has no attribute 'scan'

Any suggestions? I looked around but didn't see any similar issue, apologies if it's been addressed previously.

Thanks

**Comment by mgschwan** [comment]
Hi anxsy,

the blensor module can only be used with the official blensor binary from blensor.org not with the regular blender version from the blender website.

In the future there will be a fallback mode that allows the use of the blensor addon in the regular blender, albeit with limited functionality. But this is not yet implemented so you get the error you mentioned.

BR
Michael
