### ISSUE TITLE
Problem with installation 

### ISSUE THREAD

**Issue by mmmin1214** [mgschwan/blensor#25]
Hello there, 

I just have a problem with installing Blensor. I have tried all the version on the list of the website, however, I can not find even Sensor simulation tool in the addons - system tab. Could you help me accessing to it? I tried both Window and Mac os but both didn't work. 

Many thanks

**Comment by mgschwan** [comment]
Currently, only the Linux version is supported. Mac and Windows are outdated. But we will release a new Windows version soon.

**Comment by jaimesx** [comment]
I tried to install 1.0.18-RC8_x64 on Ubuntu 18.04 and the python module failed to install because it didn't find numpy. Even when compiling from source gives the same error.

However, I realized I had numpy installed only for python 2.x and not for python3.x which is what blensor is using. Then I installed python3-numpy, recompiled and now only the recompiled Blensor works.

It seems that the build is broken.

**Comment by clement-z** [comment]
Hello, 

I have had the same issue as jaimesx with 1.0.18-RC8_x64, on Ubuntu 17.10.
Numpy is not included in the bundled python. There is only a broken simlink.

```
# pwd
/opt/blensor/blensor_1.0.18-RC8_x64
# ll 2.79/python/lib/python3.6/site-packages
total 28
drwxr-xr-x  7 1003 1003 4096 Mar 29 13:56 ./
drwxr-xr-x 30 1003 1003 4096 Mar 29 13:56 ../
drwxr-xr-x  2 1003 1003 4096 Mar 29 13:56 certifi/
drwxr-xr-x  3 1003 1003 4096 Mar 29 13:56 chardet/
drwxr-xr-x  2 1003 1003 4096 Mar 29 13:56 idna/
lrwxrwxrwx  1 1003 1003   55 Mar 29 13:56 numpy -> /opt/lib/numpy-1.13.1/lib/python3.6/site-packages/numpy
drwxr-xr-x  2 1003 1003 4096 Mar 29 13:56 requests/
drwxr-xr-x  5 1003 1003 4096 Mar 29 13:56 urllib3/
```

Simply redirecting that simlink to an existing python3 numpy works.

```
# rm ./2.79/python/lib/python3.6/site-packages/numpy
# ln -s /usr/lib/python3/dist-packages/numpy/ ./2.79/python/lib/python3.6/site-packages/numpy
# ./blender
```

Clement

**Comment by mgschwan** [comment]
Thanks for the report. I've uploaded a new version (RC9) which fixes the symlink problem.

**Comment by mirceta** [comment]
Where have you uploaded it? It's not on the site and it's not among releases.
