### ISSUE TITLE
Cannot start blensor

### ISSUE THREAD

**Issue by mirceta** [mgschwan/blensor#26]
This is on Ubuntu 18.04 while running Blensor 1.0.18 RC 8 64-bit Ubuntu 17.04+.

The first problem was that numpy was not linked properly, but I fixed that one.

The second problem is the depenency on these 3 libraries:

```sudo apt-get install libopenjpeg2 libjpeg62 libpng12-0```

apt-get can't find 2 of these libraries, but again I installed them through packages.ubuntu.com

- It gave 2 more errors for dependencies:
  - libopenimageio
  - libjemalloc

I guess this is just a warning that he newest build does not work out of the box on Ubuntu 18.04.

**Comment by mgschwan** [comment]
I've just uploaded a new release candidate (RC10) that includes the binary of libopenimageio

As for libjemalloc can you try 

    apt-get install libjemalloc1

**Comment by mirceta** [comment]
Thanks for your reply. I already solved it by finding the libraries online. This is best meant just to inform you of the problems you can get on this specific version of Ubuntu.
