### ISSUE TITLE
Question about Sensor Coordinates in python script

### ISSUE THREAD

**Issue by marvdias** [mgschwan/blensor#27]
Hello everyone,
I am currently testing blensor's LIDAR sensor. I did a script to scan a scenario and then generate the `.pcd` files. However, I noticed that the point cloud data, when imported back to blender or PCL, is rotated and translated. I also noticed that in the blensor GUI there is the option of save or not the sensors coordinates when performing the scan. Is there any option I could set to do the same? 
I already tested the following and it did not work.
```
scanner = bpy.data.objects["Camera"]
scanner.local_coordinates = False
blensor.blendodyne.scan_advanced(scanner, rotation_speed = 10.0,simulation_fps=24, angle_resolution = 0.1728, max_distance = 120, evd_file= "./scan.pcd",
                                noise_mu=0.0, noise_sigma=0.03, start_angle = 0.0, end_angle = 360.0, evd_last_scan=False, add_blender_mesh = False,
                                add_noisy_blender_mesh = False)
```

**Comment by mgschwan** [comment]
The most common issue is that the coordinates are mirrored along the y axis. Before you try to change the reference frame try inverting the different axes first (there are the three scanner properties inv_scan_x, inv_scan_y and inv_scan_z)

That said, the parameter for the coordinate system is only valid for scans from the gui, you can however pass a world_transformation parameter to the scan function)

The default is Matrix() which is the identity matrix but you can pass world_transformation = scanner.matrix_world to have the scan appear in global coordinates.

**Comment by marvdias** [comment]
Hi @mgschwan,
My problem was not an inversion of axes, was that the scan was getting the camera position and rotation, and taking it into account when positioning the point clouds. However the world_transformation worked! Thank you very much!
