### ISSUE TITLE
Blender 2.8

### ISSUE THREAD

**Issue by francis-bitonti** [mgschwan/blensor#36]
Has anyone tried to get this to work with blender 2.8? I am having some issues getting this running. I am unable to install the supporting packages.

E: Unable to locate package libopenjpeg2
E: Package 'libpng12-0' has no installation candidate
E: Unable to locate package libboost-regex.62.0
E: Couldn't find any package by glob 'libboost-regex.62.0'
E: Couldn't find any package by regex 'libboost-regex.62.0'

**Comment by mgschwan** [comment]
Blender 2.8 is currently not possible because the Blender Internal renderer has been removed which the current Blensor version relies on.

The next version will reimplement the raytracer and thus no longer require a 2.7x Blender but that is still some time until that will be ready.
