### ISSUE TITLE
How are the scan labels generated in output pcd file?

### ISSUE THREAD

**Issue by Ritchizh** [mgschwan/blensor#47]
Hi!
I'm following PCL Tutorial, loading and scanning a scene.
In the .pcd file, produced with General Lidar sensor, there is label field: 
<p align="center">
<img src= "https://user-images.githubusercontent.com/18049634/144401080-7b360af0-6045-4059-9685-a57b3526ec3c.jpg" width="600"></p>

When I visualize unique labels with color, I get this:
<p align="center">
<img src= "https://user-images.githubusercontent.com/18049634/144401238-1144ae24-ecb3-426d-bc7d-28e8b46f51d1.jpg" width="600"></p>

Which is different from color information, where, for example, all cups have different color,  and looks like segmentation. 
Could you please tell me how were these lables generated?

**Comment by liveforday** [comment]
`Blensor-1.0.18-Blender-2.79-Winx64\2.79\scripts\addons\blensor\scan_interface_pure.py` 
line 10 of the file 
`returns_buffer[idx*ELEMENTS_PER_RETURN+4] = ord(name[0]) + (ord(name[1])<<8) + (ord(name[2])<<16) + (ord(name[3])<<24)`
blensor get value of the label according to the first four characters of the name string
